import { StyleSheet } from "react-native";

export const Style_ModalReportar = StyleSheet.create({
  Container_General: {
    // position: "absolute",
    // height: "60%",
    width: "100%",
    paddingVertical: 20,
    paddingHorizontal: 20,
    gap:20,
    // backgroundColor: "white",
    borderColor: "#dee2e6",
  },
  Card_Star: {
    flexDirection: "row",
    borderWidth: 1,
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: 10,
    borderRadius: 10,
    borderColor: "#dee2e6",
    backgroundColor: "white",
    marginVertical:10
  },
  Text_Titulo: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "500",
  },
  Text_Input: {
    borderWidth: 1,
    borderRadius: 10,
    borderColor: "#D1D0D0",
    backgroundColor: "#efeded44",
    fontSize: 16,
  },
  BtnTomarFoto: {
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "48%",
    padding: 10,
    gap: 5,
    borderRadius: 10,
    borderColor: "#D1D0D0",
    backgroundColor: "white",
  },
  BtnGrabarVideo: {
    borderWidth: 1,
    justifyContent: "center",
    alignItems: "center",
    width: "48%",
    padding: 10,
    gap: 5,
    borderRadius: 10,
    borderColor: "#D1D0D0",
    backgroundColor: "white",
  },
  BtnEnviarEva: {
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    flexDirection: "row",
    gap: 10,
    borderRadius: 10,
    backgroundColor: "#0F539C",
    width: "100%",
  },
  BtnEnviadoEva: {
    justifyContent: "center",
    alignItems: "center",
    padding: 15,
    flexDirection: "row",
    gap: 10,
    borderRadius: 10,
    backgroundColor: "white",
    width: "100%",
    borderColor:"#4CB050",
    borderWidth:1,
  },
});
